"""Canonical Conversations & AI domain contracts."""

from .models import (
    ActorType,
    Channel,
    Direction,
    DeliveryState,
    DeliveryEvidence,
    Message,
    MessageContentType,
    Conversation,
    ConversationScope,
    MediaReference,
    OrderingEvidence,
    ProcessingState,
    Provenance,
)
from .resolution import (
    ConversationKey,
    ConversationResolutionResult,
    ConversationResultStatus,
    IdentityResolutionResult,
    IdentityResultStatus,
    InMemoryConversationStore,
    PostgresConversationStore,
    resolve_conversation,
)
from .ordering import (
    OrderedMessage,
    OrderingConfidence,
    OrderingEvidence as ResolvedOrderingEvidence,
    OrderingResult,
    resolve_message_order,
)
from .turns import (
    AggregationEvidence,
    ConversationalTurn,
    TurnAggregationConfig,
    TurnBuildResult,
    TurnStatus,
    build_turns,
    stabilize_turns,
)
from .topics import (
    InMemoryTopicStore,
    PostgresTopicStore,
    Topic,
    TopicConflictError,
    TopicEvidence,
    TopicState,
    TopicStateService,
    TopicStore,
    TopicTransition,
    TopicTransitionError,
    TopicTransitionKind,
    TopicTransitionRequest,
)
from .instructions import (
    InMemoryInstructionStore, InstructionConflictError, InstructionContext,
    InstructionDraft, InstructionError, InstructionEvent, InstructionEventType,
    InstructionScope, InstructionSelection, InstructionService, InstructionStatus,
    InstructionVersion, PostgresInstructionStore, SelectionEvidence,
)

__all__ = [
    "ActorType",
    "Channel",
    "Conversation",
    "ConversationScope",
    "DeliveryState",
    "DeliveryEvidence",
    "Direction",
    "Message",
    "MessageContentType",
    "MediaReference",
    "OrderingEvidence",
    "ProcessingState",
    "Provenance",
    "ConversationKey",
    "ConversationResolutionResult",
    "ConversationResultStatus",
    "IdentityResolutionResult",
    "IdentityResultStatus",
    "InMemoryConversationStore",
    "PostgresConversationStore",
    "resolve_conversation",
    "OrderedMessage",
    "OrderingConfidence",
    "ResolvedOrderingEvidence",
    "OrderingResult",
    "resolve_message_order",
    "AggregationEvidence",
    "ConversationalTurn",
    "TurnAggregationConfig",
    "TurnBuildResult",
    "TurnStatus",
    "build_turns",
    "stabilize_turns",
    "InMemoryTopicStore",
    "PostgresTopicStore",
    "Topic",
    "TopicConflictError",
    "TopicEvidence",
    "TopicState",
    "TopicStateService",
    "TopicStore",
    "TopicTransition",
    "TopicTransitionError",
    "TopicTransitionKind",
    "TopicTransitionRequest",
]
